Fix NameError on rspec
     Failure/Error: subject!{ rake["heart_seed:xls"].invoke }
     NameError:
       undefined local variable or method `rake' for #<RSpec::ExampleGroups::HeartSeed::Xls::WhenExistsENVSHEETS:0x00000004b3d888>
     # ./spec/heart_seed/tasks/heart_seed_rake_spec.rb:76:in `block (4 levels) in <top (required)>'
     # ./spec/support/shared_contexts/rake_in_app_dir.rb:12:in `block (3 levels) in <top (required)>'
     # ./spec/support/shared_contexts/rake_in_app_dir.rb:11:in `chdir'
     # ./spec/support/shared_contexts/rake_in_app_dir.rb:11:in `block (2 levels) in <top (required)>'