Use latest rspec
```
$ rake release
rake aborted!
NoMethodError: undefined method `last_comment' for #<Rake::Application:0x007faf839cc220>
/Users/sue445/dev/workspace/github.com/sue445/heart_seed/vendor/bundle/ruby/2.4.0/gems/rspec-core-3.0.4/lib/rspec/core/rake_task.rb:101:in `define'
/Users/sue445/dev/workspace/github.com/sue445/heart_seed/vendor/bundle/ruby/2.4.0/gems/rspec-core-3.0.4/lib/rspec/core/rake_task.rb:78:in `initialize'
/Users/sue445/dev/workspace/github.com/sue445/heart_seed/Rakefile:4:in `new'
/Users/sue445/dev/workspace/github.com/sue445/heart_seed/Rakefile:4:in `<top (required)>'
/Users/sue445/dev/workspace/github.com/sue445/heart_seed/vendor/bundle/ruby/2.4.0/gems/rake-12.1.0/exe/rake:27:in `<top (required)>'
/Users/sue445/.rbenv/versions/2.4.1/bin/bundle:22:in `load'
/Users/sue445/.rbenv/versions/2.4.1/bin/bundle:22:in `<main>'
(See full trace by running task with --trace)
```

`#last_comment` is removed at rake v12.0.0
https://github.com/ruby/rake/blob/master/History.rdoc#1200

And rspec-core v3.0.x requires rake ~> 10.0.0
https://rubygems.org/gems/rspec-core/versions/3.0.0